name:GitHub Avtions Dotnet
on:
push:
paths-ignore:
  _ '**/*.md'

jobs:
   job-DotNet-Push:
    runs-on: ubuntu-latest
    env:
       DOTNET_CORE_VERSION: 7.0
       DOTNET_CLI_TELEMETRY_OUTPUT: 1
       DOTNET_CONFIGURATION: Release
       PROJECT_PATH: 'src/AppcontableCompueasys2.2'
       PROJCT_TEST_PATH: 'tests/**.tests'
       steps:
       - name: Check uot repository code ('${{ github.repository }}' cloned to runner)
       uses: actions/checkout@v2
